rabbitmq: docker run --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.13.1-management
celery: watchfiles --filter python "celery -A myshop worker -l info --pool=threads" .
flower: watchfiles --filter python "celery -A myshop flower" .
web: python manage.py runserver
stripe: stripe listen --all-snapshot --forward-to 127.0.0.1:8000/payment/webhook/
