# Generated by Django 5.0.14 on 2026-09-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="update",
            new_name="updated",
        ),
    ]
