# Generated by Django 5.0.14 on 2026-09-19 17:33

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_tags"),
    ]

    operations = [TrigramExtension()]
